[phases.setup]
aptPkgs = ['curl', 'gcc', 'g++', 'libpq-dev']

[phases.install]
cmds = [
  'pip install -r requirements.txt'
]

[phases.build]
cmds = [
  'cd backend && python -m alembic upgrade head || echo "Migration failed, continuing..."'
]

[start]
cmd = '/app/start.sh'

[variables]
PORT = '8000'