[build]
builder = "nixpacks"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8000" }
ENVIRONMENT = { default = "production" }
DEBUG = { default = "false" }
LOG_LEVEL = { default = "INFO" }