[build]
builder = "nixpacks"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "8000" }
ENVIRONMENT = { default = "production" }
DEBUG = { default = "false" }
LOG_LEVEL = { default = "INFO" }