[build]
builder = "nixpacks"
watchPatterns = ["**/*.py", "requirements.txt", "alembic/**/*"]

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/ping"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 15

[experimental]
incremental = false

[env]
PORT = { default = "8000" }
ENVIRONMENT = { default = "production" }
DEBUG = { default = "false" }
LOG_LEVEL = { default = "INFO" }