"""Add Schema.org fields to Content model

Revision ID: 791bff3b054d
Revises: 0915f7c1f01a
Create Date: 2025-07-11 19:10:58.539676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791bff3b054d'
down_revision: Union[str, Sequence[str], None] = '0915f7c1f01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('author_name', sa.String(length=100), nullable=True))
    op.add_column('content', sa.Column('publisher_name', sa.String(length=100), nullable=True))
    op.add_column('content', sa.Column('featured_image_url', sa.String(length=500), nullable=True))
    op.add_column('content', sa.Column('featured_image_alt', sa.String(length=255), nullable=True))
    op.add_column('content', sa.Column('featured_image_caption', sa.Text(), nullable=True))
    op.add_column('content', sa.Column('article_section', sa.String(length=100), nullable=True))
    op.add_column('content', sa.Column('schema_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'schema_type')
    op.drop_column('content', 'article_section')
    op.drop_column('content', 'featured_image_caption')
    op.drop_column('content', 'featured_image_alt')
    op.drop_column('content', 'featured_image_url')
    op.drop_column('content', 'publisher_name')
    op.drop_column('content', 'author_name')
    # ### end Alembic commands ###
