"""add_image_config_table

Revision ID: a004ca550688
Revises: bd4856413ff8
Create Date: 2025-07-11 22:31:31.866024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a004ca550688'
down_revision: Union[str, Sequence[str], None] = 'bd4856413ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('num_images', sa.Integer(), nullable=True),
    sa.Column('image_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'WIDE', 'TALL', name='imagesize'), nullable=True),
    sa.Column('image_quality', sa.Enum('STANDARD', 'HD', name='imagequality'), nullable=True),
    sa.Column('image_placement', sa.Enum('TOP', 'MIDDLE', 'BOTTOM', 'SCATTERED', name='imageplacement'), nullable=True),
    sa.Column('style', sa.Enum('MYSTICAL', 'ARTISTIC', 'PHOTOREALISTIC', 'WATERCOLOR', 'GOTHIC', 'FANTASY', 'MINIMALIST', 'VINTAGE', name='imagestyle'), nullable=True),
    sa.Column('auto_generate', sa.Boolean(), nullable=True),
    sa.Column('include_featured', sa.Boolean(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('custom_style', sa.Enum('MYSTICAL', 'ARTISTIC', 'PHOTOREALISTIC', 'WATERCOLOR', 'GOTHIC', 'FANTASY', 'MINIMALIST', 'VINTAGE', name='imagestyle'), nullable=True),
    sa.Column('custom_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_configs_id'), 'image_configs', ['id'], unique=False)
    op.drop_column('users', 'image_position')
    op.drop_column('users', 'images_per_post')
    op.drop_column('users', 'image_prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_prompt', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('images_per_post', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('image_position', sa.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_image_configs_id'), table_name='image_configs')
    op.drop_table('image_configs')
    # ### end Alembic commands ###
