"""Add manual_images table

Revision ID: a47bf180b10b
Revises: a9e2d85f840d
Create Date: 2025-07-12 00:22:19.714524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47bf180b10b'
down_revision: Union[str, Sequence[str], None] = 'a9e2d85f840d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_images_id'), 'manual_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_images_id'), table_name='manual_images')
    op.drop_table('manual_images')
    # ### end Alembic commands ###
