"""Add Gemini configuration fields to ImageConfig

Revision ID: a9e2d85f840d
Revises: a004ca550688
Create Date: 2025-07-12 00:03:46.686070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e2d85f840d'
down_revision: Union[str, Sequence[str], None] = 'a004ca550688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_configs', sa.Column('image_provider', sa.Enum('GEMINI', 'OPENAI', name='imageprovider'), nullable=True))
    op.add_column('image_configs', sa.Column('gemini_aspect_ratio', sa.Enum('SQUARE', 'HORIZONTAL', 'VERTICAL', 'CLASSIC', 'PORTRAIT', name='geminiaspectratio'), nullable=True))
    op.add_column('image_configs', sa.Column('gemini_safety_level', sa.Enum('BLOCK_MEDIUM_AND_ABOVE', 'BLOCK_ONLY_HIGH', 'BLOCK_LOW_AND_ABOVE', name='geminisafetylevel'), nullable=True))
    op.add_column('image_configs', sa.Column('gemini_person_generation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_configs', 'gemini_person_generation')
    op.drop_column('image_configs', 'gemini_safety_level')
    op.drop_column('image_configs', 'gemini_aspect_ratio')
    op.drop_column('image_configs', 'image_provider')
    # ### end Alembic commands ###
